repos:
- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.19.1
  hooks:
  - id: gitlint

- repo: https://github.com/psf/black
  rev: 23.9.0
  hooks:
  - id: black
    language_version: python3.11

- repo: https://github.com/python-poetry/poetry
  rev: 1.6.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
    args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
